package com.xyzbank.digital_onboarding_api.validation;

import com.xyzbank.digital_onboarding_api.enums.Country;
import jakarta.validation.Constraint;
import jakarta.validation.ConstraintValidator;
import jakarta.validation.ConstraintValidatorContext;
import jakarta.validation.Payload;

import java.lang.annotation.*;

@Constraint(validatedBy = ValidIBAN.IbanValidator.class)
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface ValidIBAN {
    String message() default "Invalid IBAN format";

    Class<?>[] groups() default {};

    Class<? extends Payload>[] payload() default {};

    class IbanValidator implements ConstraintValidator<ValidIBAN, String> {

        @Override
        public boolean isValid(String iban, ConstraintValidatorContext context) {
            if (iban == null) {
                return true; // allow null during account creation process -> generated by the persisted id
            }

            if (iban.trim().isEmpty()) {
                return false;
            }

            String cleanIban = iban.replaceAll("\\s+", "").trim();

            if (cleanIban.length() < 4) {
                return false;
            }

            String countryCode = cleanIban.substring(0, 2);

            try {
                Country country = Country.fromCode(countryCode);
                if (!country.isValidIban(cleanIban)) {
                    return false;
                }

                return validateCheckDigits(cleanIban);
            } catch (IllegalArgumentException e) {

                return validateCheckDigits(cleanIban);
            }
        }

        // follows the wikipedia Algorithms/Validating the IBAN
        // https://en.wikipedia.org/wiki/International_Bank_Account_Number
        private boolean validateCheckDigits(String iban) {
            String rearranged = iban.substring(4) + iban.substring(0, 4);

            // replace letters with numbers (A=10, B=11, ..., Z=35)
            StringBuilder numericString = new StringBuilder();
            for (char c : rearranged.toCharArray()) {
                if (Character.isLetter(c)) {
                    // Convert A=10, B=11, ..., Z=35
                    int value = Character.toUpperCase(c) - 'A' + 10;
                    numericString.append(value);
                } else {
                    numericString.append(c);
                }
            }

            int remainder = mod97(numericString.toString());
            return remainder == 1;
        }


        private int mod97(String numericString) {
            int remainder = 0;
            for (char digit : numericString.toCharArray()) {
                remainder = (remainder * 10 + Character.getNumericValue(digit)) % 97;
            }
            return remainder;
        }
    }
}